events {}
http {

  server {
    listen 80;
    
    location /python {
    proxy_pass http://python-service:5000;
    }

    location /node {
    proxy_pass http://node-service:3000;
    }
    
    location /go {
    proxy_pass http://go-service:8000;
    }
  }
}
