# stage 1 - builder

FROM golang:1.22 as builder
WORKDIR /docker-project
COPY . .
RUN go build -o main .

# stage 2 - Runtime

FROM debian:bookworm-slim
WORKDIR /docker-project
COPY --from=builder /docker-project/main .
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/list/*
CMD ["./main"]
