# Stage 1 - Tester

FROM python:3.12 AS tester
WORKDIR /docker-project
COPY requirements.txt .
RUN pip install --upgrade pip wheel setuptools && pip install --no-cache-dir -r requirements.txt
COPY . .

# stage 2- Runtime
FROM python:3.12-slim
WORKDIR /docker-project
COPY requirements.txt .
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip wheel setuptools
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "script.py"]
