# stage 1 - builder
FROM node:20-slim AS builder
WORKDIR /docker-project
COPY package*.json ./
# Install ALL dependencies to make sure OpenTelemetry components build properly
RUN npm install 
COPY . .

# stage 2 - Runtime
FROM node:20-slim
WORKDIR /docker-project
# Explicitly grab the compiled application and node_modules from builder
COPY --from=builder /docker-project /docker-project
RUN apk add --no-cache curl
CMD ["node", "index.js"]
