# stage 1 -builder

FROM node:20-alpine as builder
WORKDIR /docker-project
COPY package*.json .
RUN npm install --production
COPY . .

# stage 2- Runtime

FROM node:20-alpine
WORKDIR /docker-project
COPY --from=builder /docker-project .
RUN apk add --no-cache curl
CMD ["node","index.js"]
