name: Deployment phase

on:
  push:
    branches: [srijan]
    #workflow_run:
     # workflows: ["docker-build-push"]
      #type: [completed]
    #workflow_dispatch:


jobs:

  deployment-phase:
    runs-on: ubuntu-latest
 #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - uses: actions/checkout@v4

#synchronization branches
      - name: synchronization with branches
        run: |
          git checkout master && git pull hp srijan && git push hp master && git checkout srijan

      - name: deploying code
        run: |
          echo -e "Deploying codes...\nHold on:\nProgressing....\nSuccessfully deployed..."
          echo -e "Pulling images...\nProgressing....."
          docker pull ${{ secrets.DOCKER_USERNAME }}/dev-python:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/dev-node:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/dev-go:latest
          echo -e "Successfully pulled images..."
          echo -e "Composing docker files....\nInitializing & untag unused images....."
          docker image prune -f
          echo -e "Succesfully untagged unused images...\nStart composing files..."
          docker compose -f docker-compose.yml up -d --remove-orphans

# Zero-downtime (Automated roll back ) & scaling
      - name: rolling back to stable & scaling container
        run: |
          for SVC in python-service node-service go-service; do
            status=$(docker inspect --format='{{json .State.Health.Status}}' $(docker ps -q -f name=$SVC))
            if [[ '$status' != "\"healthy\"" ]]; then
              echo -e " $SVC is unhealthy\nRolling back to stable..."
              docker compose -f docker-compose.yml down -d
              docker pull ${{ secrets.DOCKER_USERNAME }}/dev-${SVC}:stable
              # scaling container
              docker compose -f docker-compose.yml up -d --scale ${SVC}=2
            else
              echo -e "$SVC container is healthy"
            fi
          done

  alert:
    runs-on: ubuntu-latest
    needs: [deployment-phase]
    if: failure()
    steps:
      - uses: actions/checkout@v4

      - name: sending message
        run: |
          echo -e "Deployment has been failed on:\nBranch: ${{ github.ref }}"
