name: Deployment phase

on:
  push:
    branches: [srijan]
  #workflow_run:
    #workflows: ["docker-build-push"]
    #type: [completed]
  #workflow_dispatch:

jobs:

  deployment-phase:
    runs-on: self-hosted
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - uses: actions/checkout@v4

      - name: deploying code
        run: |
          echo -e "Deploying codes...\nHold on:\nProgressing....\nSuccessfully deployed..."
          echo -e "Pulling images...\nProgressing....."
          docker pull ${{ secrets.DOCKER_USERNAME }}/dev-python:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/dev-node:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/dev-go:latest
          echo -e "Successfully pulled images..."
          echo -e "Composing docker files....\nInitializing & untag unused images....."
          docker image prune -f && docker network prune -f && docker container prune -f
          echo -e "Succesfully untagged unused images...\nStart composing files..."
          docker stack deploy -c docker-compose.yml devstack

# Zero-downtime (Automated roll back ) & scaling in swarm mode
      - name: Rolling back & scaling container on Health failure in swarm mode
        run: |
          set -euo pipefail
          for SVC in python node go; do
            echo "$SVC - service is running"
            if docker service ls --format '{{.Name}}' | grep -q "devstack_${SVC}-service"; then
              unhealthy=$(docker service ps devstack_${SVC}-service \
                --filter "desired-state=running" \
                --format "{{.CurrentState}}" | grep -v "Running" || true)

              if [ -n "$unhealthy" ]; then
                echo "$SVC service is unhealthy → attempting rollback..."
                if ! docker service update --rollback devstack_${SVC}-service; then
                  echo "Rollback not available for $SVC"
                fi
                if ! docker service scale devstack_${SVC}-service=2; then
                  echo "Scaling failed for $SVC"
                fi
              else
                echo "$SVC service is healthy"
              fi
            else
              echo "$SVC service is not running"
            fi
          done




  alert:
    runs-on: ubuntu-latest
    needs: [deployment-phase]
    if: failure()
    steps:
      - uses: actions/checkout@v4

      - name: sending message
        run: |
          echo -e "Deployment has been failed on:\nBranch: ${{ github.ref }}"
